<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<html>
<head>
<meta name="copyright" content="2000,  Bradley Kjell" />
<meta name="author" content="Bradley Kjell kjell@ieee.org " />
<meta name="robots" content="index,follow" />
<title>Exception thrown by a catch{} Block</title>
<link rel="stylesheet" type="text/css" href="../CAIstyle.css" />
</head>

<body>
<!-- generated by CSSmaker.java, version of 01/14/2003-->
<!-- from source javaChap86.frames on Tue Jul 15 18:47:31 EDT 2003 -->

<!-- ANSWER AREA -->
<p>
Does <code>DataInputStream.close()</code> throw an exception?
</p>

<div class="answer">
<h3>A good answer might be:</h3>
<p>
Yes, it throws an <code>IOException</code> 
</p>


</div>

<!-- LESSON AREA -->
<div class="lesson">
<h1>Exception thrown by a <code> catch{} </code> Block</h1>

<p>
So there is a problem.
The <code>close()</code> method inside the <code>catch{}</code> block
throws an <code>IOException</code> which is not caught.
</p>

<pre class="program">
// Loop with problems

try
{
  while ( true )
    sum += instr.readInt();
}

catch ( EOFException eof )
{
  System.out.println( "The sum is: " + sum );
  instr.close(); <span style="color:red;font-weight:bold">&lt;&#8212;&#8212; throws IOException </span>
}

catch ( IOException eof ) <span style="font:blue">&lt;&#8212;&#8212; this  catch is for the try{} block </span>
{                         <span style="font:blue">     not for the previous catch{} block</span>
  System.out.println( "Problem reading input" );
  instr.close(); <span style="color:red;font-weight:bold">&lt;&#8212;&#8212; throws IOException </span>
}
</pre> 

<p>
There are various ways to deal with this.
One possibility is not to catch the exception that <code>close()</code>
throws.
Then the method header must be 
</p>

<pre class="code">
public static void main(String[] args) throws IOException
</pre> 

</div>

<!-- QUESTION AREA -->
<div class="question">
<h3> QUESTION 10:</h3>
<a href="ch86_11.html">
<img src="../nextBut.gif" hspace="5" align="right" border="0"/></a>
<p>
Can a <code>try{}/catch{}</code> be nested inside an outer <code>try{}</code> block?
</p>

</div>

</body>
</html>
